### ISSUE TITLE
windows怎么把壁纸渲染在桌面背景上的

### ISSUE THREAD

**Issue by 1431241631** [dynamic-wallpaper/dynamic-wallpaper#3]
在你的代码里设置了`type: 'desktop'`
我把你的winConfig直接搬了下来发现只是在桌面上多了一个没有壳的窗口
因为windows桌面上有很多的图标，所以我想只想让它在桌面背景上渲染
请问有什么好的解决方案吗谢谢

**Comment by mizuka-wu** [comment]
这个目前还是给mac用的 给windows要加个electron-wallpaper
我没有win电脑 还没试

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: jiaohua ***@***.***>
发送时间: Monday, April 26, 2021 12:44:36 PM
收件人: dynamic-wallpaper/dynamic-wallpaper ***@***.***>
抄送: Subscribed ***@***.***>
主题: [dynamic-wallpaper/dynamic-wallpaper] windows怎么把壁纸渲染在桌面背景上的 (#3)


在你的代码里设置了type: 'desktop'
我把你的winConfig直接搬了下来发现只是在桌面上多了一个没有壳的窗口
因为windows桌面上有很多的图标，所以我想只想让它在桌面背景上渲染
请问有什么好的解决方案吗谢谢

―

**Comment by mizuka-wu** [comment]
顺带一提 desktop这个参数是electron文档上写过的 mac特有的选项

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 吴 贻| ***@***.***>
发送时间: Tuesday, April 27, 2021 7:34:44 AM
收件人: dynamic-wallpaper/dynamic-wallpaper ***@***.***>; dynamic-wallpaper/dynamic-wallpaper ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [dynamic-wallpaper/dynamic-wallpaper] windows怎么把壁纸渲染在桌面背景上的 (#3)

这个目前还是给mac用的 给windows要加个electron-wallpaper
我没有win电脑 还没试

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: jiaohua ***@***.***>
发送时间: Monday, April 26, 2021 12:44:36 PM
收件人: dynamic-wallpaper/dynamic-wallpaper ***@***.***>
抄送: Subscribed ***@***.***>
主题: [dynamic-wallpaper/dynamic-wallpaper] windows怎么把壁纸渲染在桌面背景上的 (#3)


在你的代码里设置了type: 'desktop'
我把你的winConfig直接搬了下来发现只是在桌面上多了一个没有壳的窗口
因为windows桌面上有很多的图标，所以我想只想让它在桌面背景上渲染
请问有什么好的解决方案吗谢谢

―
