### ISSUE TITLE
没有看到你的license,某人可以用于商业项目吗?

### ISSUE THREAD

**Issue by akss5768** [dynamic-wallpaper/dynamic-wallpaper#5]
没有看到你的license,某人可以用于商业项目吗?

**Comment by mizuka-wu** [comment]
可以的 其实这个b站大的视频那边还有点问题 还不算正式发布

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Yoki ***@***.***>
发送时间: Tuesday, June 29, 2021 4:26:27 PM
收件人: dynamic-wallpaper/dynamic-wallpaper ***@***.***>
抄送: Subscribed ***@***.***>
主题: [dynamic-wallpaper/dynamic-wallpaper] 没有看到你的license,某人可以用于商业项目吗? (#5)


没有看到你的license,某人可以用于商业项目吗?

―
